version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: spaceapidb
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  app:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: spaceapidb
      DB_DIALECT: mysql
    # Commented out for manual control:
    # command: sh -c "npx sequelize-cli db:migrate && npm start"
